import { useEffect, useState } from "react";
import { Search } from "lucide-react";
import { api } from "../api";
import { Kpi, NoticeState, Page, ProgressBar, Toast } from "../components/app-ui";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card } from "../components/ui/card";
import type { Ticket } from "../types";

export function OfficerPage(){const[tickets,setTickets]=useState<Ticket[]>([]);const[filter,setFilter]=useState("ALL");const[search,setSearch]=useState("");const[notice,setNotice]=useState<NoticeState>(null);async function refresh(){try{setTickets(await api.listTickets())}catch(e){setNotice({tone:"error",title:"Could not load ticket queue",message:e instanceof Error?e.message:"Please retry."})}}useEffect(()=>{void refresh()},[]);const shown=tickets.filter(t=>{const ok=filter==="ALL"||t.status===filter;const hay=`${t.ticket_code} ${t.category} ${t.location} ${t.department}`.toLowerCase();return ok&&hay.includes(search.trim().toLowerCase())});const kpis=[["Total",tickets.length],["New",tickets.filter(t=>t.status==="SUBMITTED").length],["Active",tickets.filter(t=>["ASSIGNED","IN_PROGRESS"].includes(t.status)).length],["Escalated",tickets.filter(t=>t.status==="ESCALATED").length],["Resolved",tickets.filter(t=>t.status==="RESOLVED").length]];async function change(t:Ticket,status:string){try{await api.updateStatus(t.ticket_code,status,`Employee updated ticket to ${status}.`);await refresh();setNotice({tone:"success",title:"Ticket updated",message:`${t.ticket_code} is now ${status.replaceAll("_"," ").toLowerCase()}.`})}catch(e){setNotice({tone:"error",title:"Status update failed",message:e instanceof Error?e.message:"Please retry."})}}
return <Page title="Ticket operations" eyebrow="Employee workspace" subtitle="Review complaint routing and see the progress of every civic ticket.">{notice&&<Toast notice={notice} onClose={()=>setNotice(null)}/>}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{kpis.map(([l,v])=><Kpi key={String(l)} label={String(l)} value={String(v)}/>)}</div><Card className="mt-6 overflow-hidden border-slate-200 shadow-panel"><div className="flex flex-col gap-3 border-b border-slate-200 bg-white p-4 lg:flex-row lg:items-center lg:justify-between"><div className="relative max-w-md flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/><input className="focus-field pl-9" placeholder="Search ticket, category, location…" value={search} onChange={e=>setSearch(e.target.value)}/></div><select className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm font-semibold" value={filter} onChange={e=>setFilter(e.target.value)}>{["ALL","SUBMITTED","ASSIGNED","IN_PROGRESS","ESCALATED","RESOLVED"].map(s=><option key={s}>{s}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Ticket","Category","Location","Department","Priority","Progress","SLA","Actions"].map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody>{shown.map(t=><tr className="border-t border-slate-100 bg-white" key={t.ticket_code}><td className="px-4 py-4 font-black text-slate-900">{t.ticket_code}<div className="mt-1 text-xs font-normal text-slate-400">{t.language}</div></td><td className="px-4 py-4">{t.category}</td><td className="px-4 py-4">{t.location}</td><td className="px-4 py-4">{t.department}</td><td className="px-4 py-4"><Badge value={t.priority}/></td><td className="px-4 py-4"><ProgressBar ticket={t} compact/></td><td className="px-4 py-4"><Badge value={t.sla_state}/></td><td className="px-4 py-4"><div className="flex flex-wrap gap-2">{t.status==="SUBMITTED"&&<Button size="sm" variant="outline" onClick={()=>change(t,"ASSIGNED")}>Accept</Button>}{["ASSIGNED","ESCALATED"].includes(t.status)&&<Button size="sm" onClick={()=>change(t,"IN_PROGRESS")}>Start work</Button>}{t.status!=="RESOLVED"&&<Button size="sm" variant="secondary" onClick={()=>change(t,"RESOLVED")}>Resolve</Button>}</div></td></tr>)}</tbody></table>{shown.length===0&&<div className="p-10 text-center text-sm text-slate-500">No tickets match this view.</div>}</div></Card></Page>}
