import { FormEvent, useState } from "react";
import { Activity, Sparkles, TicketCheck, X } from "lucide-react";
import { api, type ComplaintPayload } from "../api";
import { Field, Metric, NoticeState, TicketView, Toast } from "../components/app-ui";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import type { ComplaintAnalysis, Ticket } from "../types";

export function SubmitPage(){const[complaint,setComplaint]=useState("");const[location,setLocation]=useState("");const[landmark,setLandmark]=useState("");const[analysis,setAnalysis]=useState<ComplaintAnalysis|null>(null);const[ticket,setTicket]=useState<Ticket|null>(null);const[busy,setBusy]=useState(false);const[notice,setNotice]=useState<NoticeState>(null);const[clarify,setClarify]=useState(false);const payload:ComplaintPayload={complaint,location:location||undefined,landmark:landmark||undefined};
async function analyze(e?:FormEvent){e?.preventDefault();setBusy(true);setNotice(null);try{const result=await api.analyze(payload);setAnalysis(result);setTicket(null);if(result.missing_information.length)setClarify(true);else setNotice({tone:"success",title:"Complaint understood",message:"Review the detected category and routing, then create your ticket."})}catch(err){setNotice({tone:"error",title:"Could not analyze complaint",message:err instanceof Error?err.message:"Please try again."})}finally{setBusy(false)}}
async function create(){setBusy(true);setNotice(null);try{const result=await api.createTicket(payload);setTicket(result);setAnalysis(null);setNotice({tone:"success",title:"Ticket created",message:`${result.ticket_code} is ready to track.`})}catch(err){setNotice({tone:"error",title:"Ticket could not be created",message:err instanceof Error?err.message:"Please try again."})}finally{setBusy(false)}}
return <main className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.22em] text-teal-700">Citizen services</p><h1 className="mt-2 text-3xl font-black tracking-tight text-[#081525] sm:text-4xl">Submit a civic complaint</h1><p className="mb-8 mt-2 max-w-3xl text-sm leading-6 text-slate-500">Describe the problem naturally. You do not need to choose a category or language.</p>{notice&&<Toast notice={notice} onClose={()=>setNotice(null)}/>} {clarify&&analysis&&<Clarification analysis={analysis} location={location} setLocation={setLocation} busy={busy} onClose={()=>setClarify(false)} onContinue={async()=>{setClarify(false);await analyze()}}/>}
<div className="grid gap-6 lg:grid-cols-[.95fr_1.05fr]"><Card className="border-slate-200 shadow-panel"><CardContent className="pt-6"><form className="space-y-5" onSubmit={analyze}><Field label="What happened?"><textarea className="focus-field min-h-52 resize-y" value={complaint} onChange={e=>setComplaint(e.target.value)} placeholder="Describe the issue, where it is happening and how long it has been a problem…" maxLength={5000}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Location"><input className="focus-field" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Locality / ward / area"/></Field><Field label="Landmark (optional)"><input className="focus-field" value={landmark} onChange={e=>setLandmark(e.target.value)} placeholder="Nearby landmark"/></Field></div><Button size="lg" className="w-full" disabled={busy||complaint.trim().length<10}>{busy?<Activity className="mr-2 animate-spin" size={18}/>:<Sparkles className="mr-2" size={18}/>}Analyze complaint</Button></form></CardContent></Card><div>{!analysis&&!ticket&&<Placeholder/>}{analysis&&<Summary analysis={analysis} onCreate={create} busy={busy}/>} {ticket&&<TicketView ticket={ticket}/>}</div></div></main>}

function Summary({analysis,onCreate,busy}:{analysis:ComplaintAnalysis;onCreate:()=>void;busy:boolean}){const ready=analysis.missing_information.length===0;return <Card className="overflow-hidden border-slate-200 shadow-panel"><div className="border-b border-slate-200 bg-[#0b1f3a] px-6 py-5 text-white"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-200">Complaint understanding</p><h2 className="mt-1 text-xl font-black">{analysis.category}</h2></div><Badge value={analysis.priority}/></div></div><CardContent className="pt-6"><div className="grid gap-3 sm:grid-cols-2"><Metric label="Detected language" value={analysis.language}/><Metric label="Responsible department" value={analysis.department}/><Metric label="Location" value={analysis.location||"Needs location"}/><Metric label="Duration" value={analysis.duration||"Not stated"}/><Metric label="Priority" value={analysis.priority}/><Metric label="Status" value={ready?"Ready for ticket":"Needs one more detail"}/></div><p className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm leading-6 text-slate-600">{analysis.citizen_response}</p>{ready&&<Button size="lg" className="mt-5 w-full" onClick={onCreate} disabled={busy}><TicketCheck className="mr-2" size={18}/>Create trackable ticket</Button>}</CardContent></Card>}

function Clarification({analysis,location,setLocation,busy,onClose,onContinue}:{analysis:ComplaintAnalysis;location:string;setLocation:(v:string)=>void;busy:boolean;onClose:()=>void;onContinue:()=>void}){const asks=analysis.missing_information.includes("location");return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4 backdrop-blur-[2px]"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-5 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-700">One more detail</p><h3 className="mt-1 text-lg font-black text-slate-900">Help us route this correctly</h3></div><button className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100" onClick={onClose} aria-label="Close"><X size={17}/></button></div><p className="mt-3 text-sm leading-6 text-slate-600">{analysis.clarification_questions[0]||"Please provide the missing information."}</p>{asks&&<div className="mt-4"><input className="focus-field" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Locality / ward / landmark" autoFocus/><Button className="mt-3 w-full" onClick={onContinue} disabled={!location.trim()||busy}>{busy?"Checking…":"Continue"}</Button></div>}</div></div>}
function Placeholder(){return <Card className="border-dashed border-slate-300 bg-white/60"><CardContent className="grid min-h-[480px] place-items-center text-center"><div><Sparkles className="mx-auto text-teal-600" size={42}/><h3 className="mt-4 text-xl font-black text-slate-900">Your complaint summary will appear here</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Only useful outcome information is shown: category, department, priority, location and ticket readiness.</p></div></CardContent></Card>}
