import { FormEvent, useEffect, useState } from "react";
import { Search } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api";
import { Audit, EmptyState, NoticeState, Page, ProgressBar, ProgressCard, TicketView, Toast } from "../components/app-ui";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent } from "../components/ui/card";
import type { Ticket } from "../types";

export function MinePage(){const[tickets,setTickets]=useState<Ticket[]>([]);const[notice,setNotice]=useState<NoticeState>(null);useEffect(()=>{api.myTickets().then(setTickets).catch((e:Error)=>setNotice({tone:"error",title:"Could not load complaints",message:e.message}))},[]);return <Page title="My complaints" eyebrow="Private citizen workspace" subtitle="Only complaints submitted from your account appear here.">{notice&&<Toast notice={notice} onClose={()=>setNotice(null)}/>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tickets.map(t=><Link to={`/track?ticket=${t.ticket_code}`} key={t.ticket_code}><Card className="h-full border-slate-200 transition hover:-translate-y-1 hover:shadow-panel"><CardContent className="pt-5"><div className="flex items-center justify-between gap-3"><b>{t.ticket_code}</b><Badge value={t.status}/></div><h3 className="mt-4 text-lg font-black">{t.category}</h3><p className="mt-1 text-sm text-slate-500">{t.location} · {t.language}</p><ProgressBar ticket={t}/><div className="mt-4 flex gap-2"><Badge value={t.priority}/><Badge value={t.sla_state}/></div></CardContent></Card></Link>)}{tickets.length===0&&<EmptyState title="No complaints yet" body="Your submitted tickets will appear here."/>}</div></Page>}

export function TrackPage(){const initial=new URLSearchParams(window.location.search).get("ticket")||"";const[code,setCode]=useState(initial);const[ticket,setTicket]=useState<Ticket|null>(null);const[notice,setNotice]=useState<NoticeState>(null);const[busy,setBusy]=useState(false);async function load(e?:FormEvent){e?.preventDefault();if(!code.trim())return;setBusy(true);setNotice(null);try{setTicket(await api.getTicket(code.trim()))}catch(err){setTicket(null);setNotice({tone:"error",title:"Ticket not found",message:err instanceof Error?err.message:"Please check the ticket number."})}finally{setBusy(false)}}useEffect(()=>{if(initial)void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
return <Page title="Track complaint" eyebrow="Ticket status" subtitle="Enter a CivicResolve ticket number to view current progress.">{notice&&<Toast notice={notice} onClose={()=>setNotice(null)}/>}<form className="mb-7 flex max-w-2xl gap-2" onSubmit={load}><input className="focus-field" value={code} onChange={e=>setCode(e.target.value)} placeholder="CR-YYMMDD-XXXXXX"/><Button disabled={busy}><Search className="mr-2" size={16}/>Track</Button></form>{ticket&&<div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><div className="space-y-5"><TicketView ticket={ticket}/><ProgressCard ticket={ticket}/></div><Audit ticket={ticket}/></div>}</Page>}
