import { FormEvent, useEffect, useMemo, useState } from "react";
import { Archive, CheckCircle2, Download, FileUp, MapPin, Search, ShieldAlert, Star, Upload, UserRound, XCircle } from "lucide-react";
import { Link } from "react-router-dom";
import { api } from "../api";
import { Audit, EmptyState, Metric, NoticeState, Page, ProgressBar, ProgressCard, Toast } from "../components/app-ui";
import { ProblemMap } from "../components/problem-map";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import type { Attachment, EnrichedTicket } from "../types";

export function MinePage(){
  const[tickets,setTickets]=useState<EnrichedTicket[]>([]);const[notice,setNotice]=useState<NoticeState>(null);const[busy,setBusy]=useState("");
  async function refresh(){try{setTickets(await api.platformMine())}catch(e){setNotice({tone:"error",title:"Could not load complaints",message:e instanceof Error?e.message:"Please retry."})}}
  useEffect(()=>{void refresh()},[]);
  async function remove(code:string){if(!window.confirm("Remove this ticket from your active complaint workspace? The audit record is retained for accountability."))return;setBusy(code);try{await api.deleteTicket(code);await refresh();setNotice({tone:"success",title:"Ticket archived",message:"The ticket was removed from your active list. Accountability history is retained."})}catch(e){setNotice({tone:"error",title:"Could not archive ticket",message:e instanceof Error?e.message:"Please retry."})}finally{setBusy("")}}
  return <Page title="My complaints" eyebrow="Private citizen workspace" subtitle="Track progress, see the assigned staff member, review resolution proof and confirm whether completed work actually solved the problem.">{notice&&<Toast notice={notice} onClose={()=>setNotice(null)}/>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tickets.map(item=>{const t=item.ticket;return <Card className="group h-full overflow-hidden border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-[0_18px_45px_rgba(15,23,42,.10)] dark:border-slate-800 dark:bg-slate-900" key={t.ticket_code}><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><b className="text-sm text-slate-900 dark:text-white">{t.ticket_code}</b><p className="mt-1 text-[11px] text-slate-400">{new Date(t.created_at).toLocaleString()}</p></div><Badge value={t.status}/></div><h3 className="mt-3 text-base font-black text-slate-950 dark:text-white">{t.category}</h3><p className="mt-1 line-clamp-2 text-sm leading-5 text-slate-500 dark:text-slate-400">{t.complaint}</p><div className="mt-3 flex items-center gap-2 text-xs text-slate-500 dark:text-slate-400"><MapPin size={14}/><span className="line-clamp-1">{t.location}</span></div>{item.assignee&&<div className="mt-3 flex items-center gap-2 rounded-lg bg-teal-50 px-3 py-2 text-xs text-teal-800 dark:bg-teal-950/30 dark:text-teal-200"><UserRound size={14}/><span><b>{item.assignee.name}</b> · {item.assignee.role}</span></div>}{item.meta.emergency&&<div className="mt-3 flex items-center gap-2 rounded-lg bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700 dark:bg-rose-950/40 dark:text-rose-200"><ShieldAlert size={14}/>Safety-risk flag</div>}<ProgressBar ticket={t}/><div className="mt-4 flex items-center justify-between gap-2"><div className="flex flex-wrap gap-2"><Badge value={t.priority}/><Badge value={t.sla_state}/></div><div className="flex gap-2"><Link to={`/track?ticket=${t.ticket_code}`}><Button size="sm" variant="outline">Details</Button></Link><Button aria-label="Archive ticket" variant="danger" size="sm" disabled={busy===t.ticket_code} onClick={()=>void remove(t.ticket_code)}><Archive size={15}/></Button></div></div></CardContent></Card>})}{tickets.length===0&&<div className="md:col-span-2 xl:col-span-3"><EmptyState title="No active complaints" body="Submitted tickets appear here until you archive them."/></div>}</div></Page>
}

export function TrackPage(){
  const initial=new URLSearchParams(window.location.search).get("ticket")||"";const[code,setCode]=useState(initial);const[item,setItem]=useState<EnrichedTicket|null>(null);const[notice,setNotice]=useState<NoticeState>(null);const[busy,setBusy]=useState(false);
  async function load(e?:FormEvent){e?.preventDefault();if(!code.trim())return;setBusy(true);setNotice(null);try{setItem(await api.platformTicket(code.trim()))}catch(err){setItem(null);setNotice({tone:"error",title:"Ticket not found",message:err instanceof Error?err.message:"Please check the ticket number."})}finally{setBusy(false)}}
  useEffect(()=>{if(initial)void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
  return <Page title="Track complaint" eyebrow="Transparent progress" subtitle="View progress, assigned staff, problem location, resolution proof and the complete activity history.">{notice&&<Toast notice={notice} onClose={()=>setNotice(null)}/>}<form className="mb-6 flex max-w-xl gap-2" onSubmit={load}><input className="focus-field" value={code} onChange={e=>setCode(e.target.value)} placeholder="CR-YYMMDD-XXXXXX"/><Button disabled={busy}><Search className="mr-2" size={16}/>Track</Button></form>{item&&<TicketDetail item={item} reload={async()=>setItem(await api.platformTicket(item.ticket.ticket_code))} notify={setNotice}/>}</Page>
}

function TicketDetail({item,reload,notify}:{item:EnrichedTicket;reload:()=>Promise<void>;notify:(n:NoticeState)=>void}){
  const t=item.ticket;const[feedback,setFeedback]=useState("");const[rating,setRating]=useState(5);const[busy,setBusy]=useState(false);const[file,setFile]=useState<File|null>(null);const[openingEvidence,setOpeningEvidence]=useState("");
  const resolutionEvidence=useMemo(()=>item.attachments.filter(a=>a.kind==="RESOLUTION_EVIDENCE"),[item.attachments]);
  const citizenEvidence=useMemo(()=>item.attachments.filter(a=>a.kind!=="RESOLUTION_EVIDENCE"),[item.attachments]);
  async function confirm(resolved:boolean){setBusy(true);try{await api.confirmResolution(t.ticket_code,{resolved,rating:resolved?rating:undefined,feedback:feedback||undefined});await reload();notify({tone:"success",title:resolved?"Resolution confirmed":"Ticket reopened",message:resolved?"Thank you. Your feedback is now part of the service record.":"The issue has been returned to active work for employee review."})}catch(e){notify({tone:"error",title:"Could not update resolution",message:e instanceof Error?e.message:"Please retry."})}finally{setBusy(false)}}
  async function upload(){if(!file)return;setBusy(true);try{await api.uploadEvidence(t.ticket_code,file);setFile(null);await reload();notify({tone:"success",title:"Evidence uploaded",message:"The file is now attached to this complaint."})}catch(e){notify({tone:"error",title:"Upload failed",message:e instanceof Error?e.message:"Please retry."})}finally{setBusy(false)}}
  async function openEvidence(attachment:Attachment){setOpeningEvidence(attachment.id);try{await api.downloadEvidence(attachment.id,attachment.original_name)}catch(e){notify({tone:"error",title:"Could not open evidence",message:e instanceof Error?e.message:"Please retry."})}finally{setOpeningEvidence("")}}

  return <div className="mx-auto max-w-6xl"><div className="grid gap-5 xl:grid-cols-[minmax(0,1.15fr)_minmax(320px,.85fr)]">
    <div className="space-y-4">
      <Card className="overflow-hidden border-slate-200 shadow-panel dark:border-slate-800 dark:bg-slate-900">
        <div className="bg-[linear-gradient(135deg,#0b1f3a,#0f766e)] px-5 py-4 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-black uppercase tracking-[.18em] text-teal-100">Ticket reference</p><div className="mt-1 text-xl font-black">{t.ticket_code}</div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-200">{t.complaint}</p></div><Badge value={t.status}/></div></div>
        <CardContent className="p-4">
          <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Category" value={t.category}/><Metric label="Department" value={t.department}/><Metric label="Location" value={t.location}/><Metric label="Priority" value={t.priority}/><Metric label="SLA state" value={t.sla_state}/><Metric label="Language" value={t.language}/></div>
          <div className="mt-3 rounded-xl border border-teal-200 bg-teal-50/70 p-3 dark:border-teal-900 dark:bg-teal-950/20"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-white text-teal-700 shadow-sm dark:bg-slate-900 dark:text-teal-300"><UserRound size={17}/></span><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-teal-700 dark:text-teal-300">Assigned officer / team</p>{item.assignee?<><b className="mt-1 block text-sm text-slate-900 dark:text-white">{item.assignee.name}</b><p className="text-xs text-slate-500 dark:text-slate-400">{item.assignee.role}{item.assignee.email?` · ${item.assignee.email}`:""}</p></>:<p className="mt-1 text-sm font-semibold text-slate-600 dark:text-slate-300">Awaiting assignment</p>}</div></div></div>
          {item.meta.related_reports>1&&<p className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">This issue is grouped with <b>{item.meta.related_reports-1}</b> other related report(s), helping employees see the wider incident.</p>}
          {item.meta.resolution_note&&<div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"><b>Employee resolution note</b><p className="mt-1 leading-5">{item.meta.resolution_note}</p></div>}
          <ProgressBar ticket={t}/>
        </CardContent>
      </Card>

      <ProblemMap location={t.location} latitude={item.meta.latitude} longitude={item.meta.longitude} title="Problem location" compact />

      <Card className="border-emerald-200 bg-emerald-50/30 dark:border-emerald-900 dark:bg-emerald-950/10">
        <CardHeader className="pb-2"><CardTitle className="text-lg">Resolution evidence from staff</CardTitle></CardHeader>
        <CardContent><p className="mb-3 text-xs leading-5 text-slate-500 dark:text-slate-400">Photos, PDFs or other proof uploaded by the officer or administrator are available here for you to review before confirming resolution.</p><div className="space-y-2">{resolutionEvidence.map(a=><div className="flex flex-col gap-2 rounded-xl border border-emerald-200 bg-white p-3 sm:flex-row sm:items-center sm:justify-between dark:border-emerald-900 dark:bg-slate-900" key={a.id}><div className="min-w-0"><span className="block truncate text-sm font-bold text-slate-800 dark:text-slate-100"><FileUp className="mr-2 inline text-emerald-700" size={15}/>{a.original_name}</span><span className="mt-1 block text-xs text-slate-400">{Math.ceil(a.size_bytes/1024)} KB · uploaded {new Date(a.created_at).toLocaleString()}</span></div><Button size="sm" variant="outline" disabled={openingEvidence===a.id} onClick={()=>void openEvidence(a)}><Download className="mr-1" size={14}/>{openingEvidence===a.id?"Opening…":"Download"}</Button></div>)}{resolutionEvidence.length===0&&<p className="rounded-xl border border-dashed border-slate-300 bg-white/70 p-4 text-sm text-slate-500 dark:border-slate-700 dark:bg-slate-900/60">No resolution evidence has been uploaded by staff yet.</p>}</div></CardContent>
      </Card>

      <Card className="border-slate-200 dark:border-slate-800 dark:bg-slate-900"><CardHeader className="pb-2"><CardTitle className="text-lg">Your supporting evidence</CardTitle></CardHeader><CardContent><div className="space-y-2">{citizenEvidence.map(a=><div className="flex items-center justify-between rounded-xl border border-slate-200 p-3 text-sm dark:border-slate-700" key={a.id}><span className="min-w-0 truncate"><FileUp className="mr-2 inline text-teal-700" size={15}/>{a.original_name}</span><Button size="sm" variant="outline" disabled={openingEvidence===a.id} onClick={()=>void openEvidence(a)}><Download size={14}/></Button></div>)}{citizenEvidence.length===0&&<p className="text-sm text-slate-500">No citizen evidence uploaded yet.</p>}</div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input type="file" className="min-w-0 flex-1 text-xs" accept="image/jpeg,image/png,image/webp,video/mp4,application/pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/><Button size="sm" onClick={()=>void upload()} disabled={!file||busy}><Upload className="mr-1" size={14}/>Upload</Button></div></CardContent></Card>
    </div>

    <div className="space-y-4">
      <ProgressCard ticket={t}/>
      {t.status==="RESOLVED"&&item.meta.citizen_confirmation!=="CONFIRMED"&&<Card className="border-teal-200 bg-teal-50/60 dark:border-teal-900 dark:bg-teal-950/20"><CardHeader className="pb-2"><CardTitle className="text-lg">Was the problem actually resolved?</CardTitle></CardHeader><CardContent><p className="text-sm leading-5 text-slate-600 dark:text-slate-300">Review the resolution note and staff evidence first. If the issue remains, reopen it instead of starting over.</p><div className="mt-3 flex items-center gap-2">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)} aria-label={`${n} stars`} className={n<=rating?"text-amber-500":"text-slate-300 dark:text-slate-600"}><Star size={21} fill={n<=rating?"currentColor":"none"}/></button>)}</div><textarea className="focus-field mt-3 min-h-20" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Optional feedback about the resolution…"/><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><Button onClick={()=>void confirm(true)} disabled={busy}><CheckCircle2 className="mr-2" size={16}/>Yes, resolved</Button><Button variant="danger" onClick={()=>void confirm(false)} disabled={busy}><XCircle className="mr-2" size={16}/>No, reopen</Button></div></CardContent></Card>}
      {item.meta.citizen_confirmation==="CONFIRMED"&&<div className="flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"><CheckCircle2/><div><b>Resolution confirmed by citizen</b>{item.meta.rating&&<p className="mt-1">Citizen rating: {item.meta.rating}/5</p>}</div></div>}
      <Audit ticket={t}/>
    </div>
  </div></div>
}
