import { FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, BarChart3, Bot, Building2, CheckCircle2, Landmark, Languages, LockKeyhole, LogOut, Search, Send, ShieldCheck, Sparkles, TicketCheck, UserPlus, Workflow } from "lucide-react";
import { Link, NavLink, Route, Routes } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, type ComplaintPayload } from "./api";
import { Badge } from "./components/ui/badge";
import { Button } from "./components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "./components/ui/card";
import type { Analytics, ComplaintAnalysis, Ticket, User } from "./types";
import { cn } from "./lib/utils";

export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.me().then(setUser).catch(() => setUser(null)).finally(() => setLoading(false)); }, []);
  if (loading) return <div className="grid min-h-screen place-items-center bg-slate-950 text-white"><Activity className="animate-spin" /></div>;
  if (!user) return <AuthPage onAuth={setUser} />;
  return <Shell user={user} onLogout={async () => { await api.logout(); setUser(null); }} />;
}

function AuthPage({ onAuth }: { onAuth: (u: User) => void }) {
  const [mode, setMode] = useState<"login" | "signup">("login");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const rules = [password.length >= 10, /[A-Z]/.test(password), /[a-z]/.test(password), /\d/.test(password), /[^A-Za-z0-9]/.test(password)];
  async function submit(e: FormEvent) { e.preventDefault(); setBusy(true); setError(""); try { onAuth(mode === "signup" ? await api.signUp({ name, email, password }) : await api.login({ email, password })); } catch (x) { setError(x instanceof Error ? x.message : "Authentication failed."); } finally { setBusy(false); } }
  return <div className="auth-shell min-h-screen px-4 py-10 text-white"><div className="mx-auto grid min-h-[85vh] max-w-6xl overflow-hidden rounded-[28px] border border-white/10 bg-white/5 shadow-2xl backdrop-blur lg:grid-cols-2">
    <div className="hidden flex-col justify-between p-12 lg:flex"><div><div className="flex items-center gap-3 text-xl font-bold"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-500"><Landmark /></span>CivicResolve AI</div><h1 className="mt-20 text-5xl font-black leading-tight">Your civic complaint.<br/><span className="text-blue-300">Understood automatically.</span></h1><p className="mt-6 max-w-lg text-lg leading-8 text-slate-300">Write the issue in your own language. The system detects the language, understands the civic problem, asks only for missing details and routes the complaint.</p></div><div className="grid grid-cols-3 gap-3 text-sm text-slate-300">{[[Languages,"Auto language"],[Workflow,"Agent pipeline"],[ShieldCheck,"Private workspace"]].map(([I,t])=>{const Icon=I as typeof Languages;return <div className="rounded-2xl border border-white/10 bg-white/5 p-4" key={String(t)}><Icon className="mb-3 text-blue-300"/>{String(t)}</div>})}</div></div>
    <div className="m-2 rounded-[24px] bg-white p-6 text-slate-900 sm:p-10 lg:m-4 lg:p-12"><div className="mx-auto max-w-md"><p className="text-xs font-bold uppercase tracking-[.22em] text-civic-600">Secure citizen access</p><h2 className="mt-3 text-3xl font-black">{mode === "login" ? "Welcome back" : "Create your account"}</h2><p className="mt-2 text-sm text-slate-500">{mode === "login" ? "Sign in to submit and track your complaints." : "New users can create a citizen account using a Gmail address."}</p>
      <div className="mt-6 grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button className={cn("rounded-lg px-3 py-2 text-sm font-bold",mode==="login"&&"bg-white shadow")} onClick={()=>{setMode("login");setError("")}}>Sign in</button><button className={cn("rounded-lg px-3 py-2 text-sm font-bold",mode==="signup"&&"bg-white shadow")} onClick={()=>{setMode("signup");setError("")}}>New user</button></div>
      <form className="mt-6 space-y-4" onSubmit={submit}>{mode==="signup"&&<Field label="Full name"><input className="focus-field" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required minLength={2}/></Field>}<Field label="Gmail address"><input className="focus-field" type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@gmail.com" required/></Field><Field label="Password"><input className="focus-field" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></Field>
      {mode==="signup"&&<div className="grid grid-cols-2 gap-2 text-xs">{["10+ characters","Uppercase","Lowercase","Number","Special character"].map((r,i)=><span className={rules[i]?"text-emerald-700":"text-slate-400"} key={r}>✓ {r}</span>)}</div>}{error&&<ErrorBox>{error}</ErrorBox>}<Button size="lg" className="w-full" disabled={busy}>{busy?<Activity className="mr-2 animate-spin"/>:mode==="login"?<LockKeyhole className="mr-2"/>:<UserPlus className="mr-2"/>}{mode==="login"?"Sign in":"Create citizen account"}</Button></form><p className="mt-5 text-xs leading-5 text-slate-400">This prototype validates Gmail format. Email ownership verification should use OTP/link verification in a real deployment.</p></div></div>
  </div></div>;
}

function Shell({user,onLogout}:{user:User;onLogout:()=>void}) {
 const staff=["OFFICER","ADMIN"].includes(user.role); const admin=user.role==="ADMIN";
 const nav:[string,string,typeof Send][]=[["/","Overview",Landmark],["/submit","Submit",Send],["/mine","My complaints",TicketCheck],["/track","Track",Search],["/command-center","AI Center",Workflow]]; if(staff)nav.push(["/officer","Officer",Building2]);if(admin)nav.push(["/admin","Admin",BarChart3]);
 return <div className="min-h-screen bg-[#f4f7fb]"><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-5 px-4 py-3 lg:px-8"><Link to="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-civic-900 text-white"><Landmark size={20}/></span><span><b>CivicResolve AI</b><small className="block text-[10px] font-bold uppercase tracking-widest text-civic-600">Citizen intelligence</small></span></Link><nav className="ml-auto hidden gap-1 lg:flex">{nav.map(([p,l,I])=><NavLink key={p} to={p} className={({isActive})=>cn("flex items-center gap-2 rounded-lg px-3 py-2 text-sm font-semibold",isActive?"bg-civic-50 text-civic-700":"text-slate-500 hover:bg-slate-100")}><I size={15}/>{l}</NavLink>)}</nav><div className="ml-auto flex items-center gap-2 lg:ml-2"><div className="hidden text-right sm:block"><div className="text-xs font-bold">{user.name}</div><div className="text-[11px] text-slate-400">{user.role}</div></div><Button size="sm" variant="outline" onClick={onLogout}><LogOut size={15}/></Button></div></div></header><Routes><Route path="/" element={<Home user={user}/>}/><Route path="/submit" element={<Submit/>}/><Route path="/mine" element={<Mine/>}/><Route path="/track" element={<Track/>}/><Route path="/command-center" element={<CommandCenter/>}/><Route path="/officer" element={staff?<Officer/>:<Denied/>}/><Route path="/admin" element={admin?<Admin/>:<Denied/>}/></Routes><footer className="border-t bg-white px-4 py-6 text-center text-xs text-slate-400">Prototype · configurable SLA rules · synthetic analytics · no official government dispatch</footer></div>
}

function Home({user}:{user:User}) {return <main><section className="hero-mesh border-b"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-24"><div><span className="inline-flex rounded-full border border-blue-100 bg-white px-3 py-1.5 text-xs font-bold text-civic-700"><Sparkles size={14} className="mr-2"/>Automatic multilingual civic intelligence</span><h1 className="mt-6 text-4xl font-black tracking-[-.04em] text-slate-950 sm:text-6xl">Tell us what happened — <span className="text-civic-600">in your own language.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">No preset scenarios. No category dropdown. CivicResolve detects the language and problem, then turns the complaint into a structured government-service workflow.</p><div className="mt-8 flex gap-3"><Link to="/submit"><Button size="lg">Submit complaint <ArrowRight className="ml-2"/></Button></Link><Link to="/mine"><Button size="lg" variant="outline">My complaints</Button></Link></div><p className="mt-6 text-sm text-slate-400">Signed in as {user.email}</p></div><Card className="shadow-panel"><CardHeader><CardTitle>AI analysis pipeline</CardTitle></CardHeader><CardContent className="space-y-3">{["Detect language & script","Understand civic problem","Extract location & duration","Assess urgency","Route to department","Create & monitor ticket"].map((x,i)=><div className="flex items-center gap-3 rounded-xl border bg-white p-3" key={x}><span className="grid h-8 w-8 place-items-center rounded-full bg-civic-50 text-sm font-black text-civic-700">{i+1}</span><b className="text-sm">{x}</b>{i<5&&<ArrowRight size={16} className="ml-auto text-slate-300"/>}</div>)}</CardContent></Card></div></section></main>}

function Submit(){const [complaint,setComplaint]=useState("");const[location,setLocation]=useState("");const[landmark,setLandmark]=useState("");const[analysis,setAnalysis]=useState<ComplaintAnalysis|null>(null);const[ticket,setTicket]=useState<Ticket|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const payload:ComplaintPayload={complaint,location:location||undefined,landmark:landmark||undefined};async function analyze(e?:FormEvent){e?.preventDefault();setBusy(true);setError("");try{setAnalysis(await api.analyze(payload));setTicket(null)}catch(x){setError(x instanceof Error?x.message:"Analysis failed") }finally{setBusy(false)}}async function create(){setBusy(true);try{setTicket(await api.createTicket(payload));setAnalysis(null)}catch(x){setError(x instanceof Error?x.message:"Ticket creation failed")}finally{setBusy(false)}}return <Page title="Describe the civic issue" eyebrow="Citizen complaint" subtitle="Write naturally in the language you use. Language and category are detected automatically."><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><Card className="shadow-panel"><CardContent className="pt-6"><form className="space-y-4" onSubmit={analyze}><div className="rounded-xl border border-blue-100 bg-blue-50 p-3 text-sm text-blue-900"><Languages className="mr-2 inline" size={17}/><b>Automatic detection:</b> do not translate or select a category.</div><Field label="What happened?"><textarea className="focus-field min-h-48 resize-y" value={complaint} onChange={e=>setComplaint(e.target.value)} placeholder="Describe the civic problem, how long it has existed, and anything that makes it urgent…" maxLength={5000}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Location (recommended)"><input className="focus-field" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Locality / ward / area"/></Field><Field label="Landmark (optional)"><input className="focus-field" value={landmark} onChange={e=>setLandmark(e.target.value)} /></Field></div><Button size="lg" className="w-full" disabled={busy||complaint.trim().length<10}>{busy?<Activity className="mr-2 animate-spin"/>:<Sparkles className="mr-2"/>}Analyze complaint</Button>{error&&<ErrorBox>{error}</ErrorBox>}</form></CardContent></Card><div>{!analysis&&!ticket&&<EmptyPanel/>}{analysis&&<AnalysisView analysis={analysis} location={location} setLocation={setLocation} reanalyze={()=>analyze()} create={create} busy={busy}/>} {ticket&&<TicketView ticket={ticket}/>}</div></div></Page>}

function AnalysisView({analysis,location,setLocation,reanalyze,create,busy}:{analysis:ComplaintAnalysis;location:string;setLocation:(v:string)=>void;reanalyze:()=>void;create:()=>void;busy:boolean}){const needs=analysis.missing_information.includes("location");return <div className="space-y-4"><Card className="shadow-panel"><CardHeader><div className="flex items-center justify-between"><CardTitle>AI Analysis</CardTitle><Badge value={analysis.priority}/></div></CardHeader><CardContent><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Metric label="Detected language" value={`${analysis.language} (${analysis.language_code})`}/><Metric label="Writing system" value={analysis.detected_script}/><Metric label="Category" value={analysis.category}/><Metric label="Location" value={analysis.location||"Missing"}/><Metric label="Duration" value={analysis.duration||"Not stated"}/><Metric label="Department" value={analysis.department}/><Metric label="Urgency" value={analysis.urgency}/><Metric label="Confidence" value={`${Math.round(analysis.confidence*100)}%`}/><Metric label="Analysis mode" value={analysis.analysis_mode}/></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-700">{analysis.reasoning_summary}</p></CardContent></Card>{analysis.missing_information.length>0&&<Card className="border-amber-200"><CardContent className="pt-5"><b>More information needed</b>{analysis.clarification_questions.map(q=><p className="mt-2 text-sm" key={q}>{q}</p>)}{needs&&<div className="mt-4 flex gap-2"><input className="focus-field" value={location} onChange={e=>setLocation(e.target.value)} placeholder="Locality / ward / landmark"/><Button onClick={reanalyze} disabled={!location.trim()||busy}>Continue</Button></div>}</CardContent></Card>}<AgentTrace analysis={analysis}/>{analysis.missing_information.length===0&&<Button size="lg" className="w-full" onClick={create} disabled={busy}><TicketCheck className="mr-2"/>Create trackable ticket</Button>}</div>}

function Mine(){const[tickets,setTickets]=useState<Ticket[]>([]);const[error,setError]=useState("");useEffect(()=>{api.myTickets().then(setTickets).catch(e=>setError(e.message))},[]);return <Page title="My complaints" eyebrow="Private citizen workspace" subtitle="Only complaints submitted from your signed-in account appear here.">{error&&<ErrorBox>{error}</ErrorBox>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{tickets.map(t=><Link to={`/track?ticket=${t.ticket_code}`} key={t.ticket_code}><Card className="h-full transition hover:-translate-y-1 hover:shadow-panel"><CardContent className="pt-5"><div className="flex justify-between"><b>{t.ticket_code}</b><Badge value={t.status}/></div><h3 className="mt-4 font-bold">{t.category}</h3><p className="mt-1 text-sm text-slate-500">{t.location} · {t.language}</p><div className="mt-4 flex gap-2"><Badge value={t.priority}/><Badge value={t.sla_state}/></div></CardContent></Card></Link>)}{tickets.length===0&&<p className="text-sm text-slate-500">No complaints submitted yet.</p>}</div></Page>}

function Track(){const initial=new URLSearchParams(location.search).get("ticket")||"";const[code,setCode]=useState(initial);const[ticket,setTicket]=useState<Ticket|null>(null);const[error,setError]=useState("");async function load(e?:FormEvent){e?.preventDefault();try{setTicket(await api.getTicket(code));setError("")}catch(x){setTicket(null);setError(x instanceof Error?x.message:"Ticket not found")}}useEffect(()=>{if(initial)void load()},[]);return <Page title="Track complaint" eyebrow="Status & audit" subtitle="Track a ticket that belongs to your account."><form className="mb-6 flex gap-2" onSubmit={load}><input className="focus-field" value={code} onChange={e=>setCode(e.target.value)} placeholder="CR-YYMMDD-XXXXXX"/><Button><Search className="mr-2" size={16}/>Track</Button></form>{error&&<ErrorBox>{error}</ErrorBox>}{ticket&&<div className="grid gap-6 lg:grid-cols-2"><TicketView ticket={ticket}/><Audit ticket={ticket}/></div>}</Page>}

function CommandCenter(){const[text,setText]=useState("");const[a,setA]=useState<ComplaintAnalysis|null>(null);const[busy,setBusy]=useState(false);async function run(){setBusy(true);try{setA(await api.analyze({complaint:text}))}finally{setBusy(false)}}return <div className="command-bg min-h-[calc(100vh-65px)] text-white"><div className="mx-auto max-w-6xl px-4 py-12"><p className="text-xs font-bold uppercase tracking-[.25em] text-blue-300">AI Command Center</p><h1 className="mt-3 text-4xl font-black">Inspect the real complaint pipeline</h1><p className="mt-3 max-w-2xl text-slate-300">No preset scenario. Type any civic complaint and inspect language detection, classification and every agent stage.</p><div className="mt-8 grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border border-white/10 bg-white/5 p-5"><textarea className="min-h-48 w-full rounded-xl border border-white/10 bg-slate-900 p-4 text-white outline-none" value={text} onChange={e=>setText(e.target.value)} placeholder="Type a complaint in any language…"/><Button className="mt-3 w-full" onClick={run} disabled={busy||text.trim().length<10}>{busy?"Analyzing…":"Run agents"}</Button>{a&&<div className="mt-5 grid grid-cols-2 gap-3"><DarkMetric label="Language" value={a.language}/><DarkMetric label="Category" value={a.category}/><DarkMetric label="Priority" value={a.priority}/><DarkMetric label="Department" value={a.department}/></div>}</div><div>{a?<div className="space-y-3">{a.agent_trace.map((s,i)=><div className="rounded-2xl border border-white/10 bg-white/5 p-4" key={s.name}><div className="flex gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-blue-500/20 text-sm font-black text-blue-200">{i+1}</span><div><div className="font-bold">{s.name}</div><div className="mt-1 text-xs text-blue-300">{s.status} · {s.processing_ms} ms</div><p className="mt-2 text-sm text-slate-300">{s.output}</p></div></div></div>)}</div>:<div className="grid min-h-80 place-items-center rounded-2xl border border-dashed border-white/15 text-slate-400"><Bot size={42}/></div>}</div></div></div></div>}

function Officer(){const[tickets,setTickets]=useState<Ticket[]>([]);const[error,setError]=useState("");const refresh=()=>api.listTickets().then(setTickets).catch(e=>setError(e.message));useEffect(()=>{void refresh()},[]);async function change(t:Ticket,status:string){await api.updateStatus(t.ticket_code,status);await refresh()}return <Page title="Officer operations" eyebrow="Staff-only" subtitle="Department queue with language, routing, urgency and SLA context.">{error&&<ErrorBox>{error}</ErrorBox>}<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr>{["Ticket","Language","Category","Location","Priority","SLA","Status","Actions"].map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{tickets.map(t=><tr className="border-t" key={t.ticket_code}><td className="px-4 py-3 font-bold">{t.ticket_code}</td><td className="px-4 py-3">{t.language}</td><td className="px-4 py-3">{t.category}</td><td className="px-4 py-3">{t.location}</td><td className="px-4 py-3"><Badge value={t.priority}/></td><td className="px-4 py-3"><Badge value={t.sla_state}/></td><td className="px-4 py-3">{t.status}</td><td className="px-4 py-3"><div className="flex gap-2">{t.status==="SUBMITTED"&&<Button size="sm" variant="outline" onClick={()=>change(t,"ASSIGNED")}>Accept</Button>}{t.status!=="RESOLVED"&&<Button size="sm" onClick={()=>change(t,"IN_PROGRESS")}>Progress</Button>}</div></td></tr>)}</tbody></table></div></Card></Page>}

function Admin(){const[a,setA]=useState<Analytics|null>(null);useEffect(()=>{api.analytics().then(setA)},[]);const data=useMemo(()=>Object.entries(a?.by_category||{}).map(([name,value])=>({name,value})),[a]);return <Page title="Admin analytics" eyebrow="Admin-only · Synthetic / Demo Data" subtitle="Prototype operational analytics from locally created tickets.">{a&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Total" value={a.total}/><Kpi label="Pending" value={a.pending}/><Kpi label="Resolved" value={a.resolved}/><Kpi label="SLA compliance" value={`${a.sla_compliance}%`}/></div><Card className="mt-6"><CardHeader><CardTitle>Complaints by category</CardTitle></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" fontSize={10}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#3159a7" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></CardContent></Card></>}</Page>}

function Page({title,eyebrow,subtitle,children}:{title:string;eyebrow:string;subtitle:string;children:React.ReactNode}){return <main className="mx-auto max-w-7xl px-4 py-10 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.22em] text-civic-600">{eyebrow}</p><h1 className="mt-2 text-3xl font-black tracking-tight">{title}</h1><p className="mt-2 mb-8 max-w-3xl text-sm leading-6 text-slate-500">{subtitle}</p>{children}</main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span>{children}</label>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-xl border bg-white p-3"><div className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-sm font-bold text-slate-900">{value}</div></div>}
function DarkMetric({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-white/5 p-3"><div className="text-[10px] uppercase tracking-wider text-slate-400">{label}</div><b className="mt-1 block text-sm">{value}</b></div>}
function Kpi({label,value}:{label:string;value:string|number}){return <Card><CardContent className="pt-5"><div className="text-xs font-bold uppercase text-slate-400">{label}</div><div className="mt-2 text-3xl font-black">{value}</div></CardContent></Card>}
function ErrorBox({children}:{children:React.ReactNode}){return <div className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{children}</div>}
function EmptyPanel(){return <Card className="border-dashed"><CardContent className="grid min-h-[500px] place-items-center text-center"><div><Bot className="mx-auto text-civic-500" size={48}/><h3 className="mt-4 text-xl font-bold">AI analysis appears here</h3><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Language, script, civic category, urgency, department, missing information and agent trace will come from the backend.</p></div></CardContent></Card>}
function AgentTrace({analysis}:{analysis:ComplaintAnalysis}){return <Card><CardHeader><CardTitle>Agent execution</CardTitle></CardHeader><CardContent className="space-y-3">{analysis.agent_trace.map((s,i)=><div className="flex gap-3 rounded-xl border p-3" key={s.name}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-civic-50 text-xs font-black text-civic-700">{i+1}</span><div><div className="font-bold">{s.name}</div><div className="text-xs text-civic-600">{s.status} · {s.processing_ms} ms</div><p className="mt-1 text-sm text-slate-500">{s.output}</p></div></div>)}</CardContent></Card>}
function TicketView({ticket}:{ticket:Ticket}){return <Card className="overflow-hidden shadow-panel"><div className="bg-emerald-700 p-5 text-white"><p className="text-xs font-bold uppercase tracking-widest text-emerald-100">Ticket</p><div className="mt-1 text-2xl font-black">{ticket.ticket_code}</div></div><CardContent className="pt-5"><div className="grid gap-3 sm:grid-cols-2"><Metric label="Status" value={ticket.status}/><Metric label="Language" value={ticket.language}/><Metric label="Category" value={ticket.category}/><Metric label="Department" value={ticket.department}/><Metric label="Location" value={ticket.location}/><Metric label="SLA" value={ticket.sla_state}/></div><p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{ticket.citizen_response}</p><Link to={`/track?ticket=${ticket.ticket_code}`}><Button className="mt-4">Track complaint</Button></Link></CardContent></Card>}
function Audit({ticket}:{ticket:Ticket}){return <Card><CardHeader><CardTitle>Audit history</CardTitle></CardHeader><CardContent className="space-y-4">{ticket.audit_events.map((e,i)=><div className="flex gap-3" key={`${e.event}-${i}`}><CheckCircle2 className="mt-0.5 text-emerald-600" size={18}/><div><b className="text-sm">{e.event.replaceAll("_"," ")}</b><p className="text-sm text-slate-500">{e.detail}</p><small className="text-slate-400">{new Date(e.created_at).toLocaleString()}</small></div></div>)}</CardContent></Card>}
function Denied(){return <Page title="Access restricted" eyebrow="Authorization" subtitle="This workspace requires an officer or administrator role."><Card><CardContent className="py-12 text-center"><ShieldCheck className="mx-auto text-civic-600" size={44}/><p className="mt-4 text-slate-500">Citizen accounts cannot access staff operations.</p></CardContent></Card></Page>}
